### ISSUE TITLE
Crash: NoClassDefFoundError: gregtech/api (modpack without Gregtech)

### ISSUE THREAD

**Issue by Krutoy242** [PrototypeTrousers/Applied-Energistics-2#90]
Using AE2 causing crash, that cant be avoided. Server crashes again and again even without players.
Crashes starts when player order a craft.

**Additional context**
[crash-2022-03-16_07.01.29-server.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/8259698/crash-2022-03-16_07.01.29-server.txt)

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7-extended_life-v51c
- Forge Version: 14.23.5.2860

**Comment by PrototypeTrousers** [comment]
its (hopefully) fixed in v51d, but use 51e instead :+1:

**Comment by Krutoy242** [comment]
Using **v51e**, still crashing when using AE:

[crash-2022-03-18_09.05.14-server.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/8303130/crash-2022-03-18_09.05.14-server.txt)

**Comment by Dragonfist07** [comment]
got the same problem with 51g
[crash-2022-03-27_14.28.42-server.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/8357865/crash-2022-03-27_14.28.42-server.txt)
